services:
  dynamodb-local:
    image: amazon/dynamodb-local:3.3.0
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'

  localstack:
    image: localstack/localstack:4.14.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=kms
